apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  labels:
    app: result

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
        app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - name: {{ .Values.result.name }}
          image: "{{ .Values.result.repository }}:{{ .Values.result.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}