apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: vote

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
        app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: {{ .Values.vote.name }}
          image: "{{ .Values.vote.repository }}:{{ .Values.vote.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}