apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
        app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: {{ .Values.worker.name }}
          image: "{{ .Values.worker.repository }}:{{ .Values.worker.tag | default .Chart.AppVersion }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}