apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: worker-deploy
  name: worker-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: worker-deploy
    spec:
      containers:
      - image: dijamonthabeatz/worker:main
        name: worker
        resources: {}
status: {}
